services:
  - type: web
    name: future-ai-backend
    env: node
    rootDirectory: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        fromService:
          name: future-ai-backend
          type: env
          key: OPENAI_API_KEY
      - key: STABILITY_API_KEY
        fromService:
          name: future-ai-backend
          type: env
          key: STABILITY_API_KEY
    plan: free
    region: oregon
