services:
  - type: web
    name: future-ai-backend
    env: node
    region: oregon  # Choose the region closest to your users
    plan: free
    
    # Build configuration
    rootDirectory: server
    buildCommand: ./render-build.sh
    
    # Start command
    startCommand: npm start
    
    # Environment variables
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        fromService:
          name: future-ai-backend
          type: env
          key: OPENAI_API_KEY
    
    # Optional: Uncomment and configure if you want to enable video generation
    # - key: STABILITY_API_KEY
    #   fromService:
    #     name: future-ai-backend
    #     type: env
    #     key: STABILITY_API_KEY
    
    # Health check path (adjust if your app has a health check endpoint)
    healthCheckPath: /
    
    # Auto-deploy from GitHub (configure in Render dashboard)
    autoDeploy: true
