services:
  - type: web
    name: future-ai-backend
    env: node
    rootDirectory: server
    buildCommand: |
      npm install -g npm@latest
      npm ci
    startCommand: node --no-warnings index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.x
      - key: OPENAI_API_KEY
        fromService:
          name: future-ai-backend
          type: env
          key: OPENAI_API_KEY
      # STABILITY_API_KEY is optional - uncomment and add if you want to enable video generation
      # - key: STABILITY_API_KEY
      #   fromService:
      #     name: future-ai-backend
      #     type: env
      #     key: STABILITY_API_KEY
    healthCheckPath: /
    plan: free
    region: oregon
